create table menu_item (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  description text,
  category varchar(255) not null,
  inventory_count int not null default 1,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE POLICY "Enable access to all users" ON public.menu_item FOR
SELECT
  USING (true);

CREATE POLICY "only admin can insert"
  ON public.menu_item
  FOR UPDATE USING (
    auth.email() = -- <admin email with single quotes>
  ) WITH CHECK (
    auth.email() = -- <admin email with single quotes>
  );

CREATE POLICY "only admin can update"
  ON public.menu_item
  FOR INSERT WITH CHECK (
    auth.email() = -- <admin email with single quotes>
  );

CREATE POLICY "only admin can delete"
  ON public.menu_item
  FOR DELETE USING (
    auth.email() = -- <admin email with single quotes>
  );