create table category (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  path ltree not null,
  has_header boolean not null default true
);

CREATE POLICY "Enable access to all users" ON public.category FOR
SELECT
  USING (true);

CREATE POLICY "only admin can insert"
  ON public.category
  FOR UPDATE USING (
    auth.email() = -- <admin email with single quotes>
  ) WITH CHECK (
    auth.email() = -- <admin email with single quotes>
  );

CREATE POLICY "only admin can update"
  ON public.category
  FOR INSERT WITH CHECK (
    auth.email() = -- <admin email with single quotes>
  );

CREATE POLICY "only admin can delete"
  ON public.category
  FOR DELETE USING (
    auth.email() = -- <admin email with single quotes>
  );